[project]
name = "ttgdt-timetable-parser"
version = "0.1.0"
description = "Ttgdt website lessons timetable parser"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.12.15",
    "beautifulsoup4>=4.14.2",
    "lxml>=6.0.2",
    "pydantic>=2.11.9",
]
